### ISSUE TITLE
测试出现问题

### ISSUE THREAD

**Issue by 1632325673** [GinZhu/RDST#1]
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    tester.test()
  File "/data2/qinfl_home/home/RDST-main/models/trans_sr_tester.py", line 200, in test
    eva_report, inference_cost = self.evaluation(pid, self.DS)
  File "/data2/qinfl_home/home/RDST-main/models/basic_tester.py", line 172, in evaluation
    eva_report = self.eva_func(rec_imgs, ori_samples)
  File "/data2/qinfl_home/home/RDST-main/metrics/sr_evaluation.py", line 152, in __call__
    report_with_scale = self.func(gt_imgs, rec_imgs_with_scale, int(np.ceil(s)))
  File "/data2/qinfl_home/home/RDST-main/metrics/sr_metrics.py", line 72, in __call__
    s = func(g, p)
  File "/data2/qinfl_home/home/RDST-main/metrics/sr_metrics.py", line 13, in ssim
    return structural_similarity(GT, P, data_range=1, multichannel=False)
  File "/data2/qinfl_home/home/anaconda3/envs/RDST/lib/python3.8/site-packages/skimage/metrics/_structural_similarity.py", line 178, inty
    raise ValueError(
ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the functionalue less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to esponding to the channels.

你好，请问出现这个问题是因为python版本问题还是测试集的问题，但是我就是用你本来的数据集呀

**Comment by GinZhu** [comment]
Dengpending on the error: "win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the functionalue less than or equal to the smaller side of your images." Could you please check wether the dataloader has loaded the data correctly? I may suggest you to call the dataloader and plot its output sample.
