### ISSUE TITLE
Training Model

### ISSUE THREAD

**Issue by jojupiter** [GinZhu/RDST#2]
I can't train the model. I get this error. Can you please help me?

Traceback (most recent call last):
  File "/content/RDST/train.py", line 57, in <module>
    ds_train = OASISMultiSRTrain(paras)
  File "/content/RDST/datasets/OASIS_dataset.py", line 122, in __init__
    self.loading()
  File "/content/RDST/datasets/OASIS_dataset.py", line 72, in loading
    image_path = glob(join(self.raw_data_folder, pid, self.image_folder, '*masked_gfc.img'))[0]
IndexError: list index out of range

**Comment by GinZhu** [comment]
This is related to the OASIS dataset. Are you using the same dataset? If so, please check whether the file name and path is correct. I suggest you to modify this "*masked_gfc.img" with your data.

**Comment by naive-ikun** [comment]
I am particularly impressed by your work and interested in conducting a detailed analysis based on similar parameters. To ensure the accuracy and compatibility of my data with the methodologies you employed, I would be very grateful if you could provide me with the specific data format you used in your study.Thank you
